2019-07-31 19:28:23.301 [error] <0.303.0>@Elixir.Events:handle_in:6 gen_server 'Elixir.Events' terminated with reason: no function clause matching 'Elixir.Events':handle_in(#{'__struct__' => 'Elixir.Requests.RequestAThing',context => #{},correlation_id => <<>>,reply_to => ...,...}) line 6
2019-07-31 19:28:23.313 [error] <0.303.0>@Elixir.Events:handle_in:6 CRASH REPORT Process 'Elixir.Events' with 0 neighbours crashed with reason: no function clause matching 'Elixir.Events':handle_in(#{'__struct__' => 'Elixir.Requests.RequestAThing',context => #{},correlation_id => <<>>,reply_to => ...,...}) line 6
2019-07-31 19:28:23.313 [error] <0.301.0>@Elixir.Events:handle_in:6 Supervisor 'Elixir.RailwayIpc.Consumer.Supervisor' had child 'Elixir.Events' started with 'Elixir.Events':start_link([]) at <0.303.0> exit with reason no function clause matching 'Elixir.Events':handle_in(#{'__struct__' => 'Elixir.Requests.RequestAThing',context => #{},correlation_id => <<>>,reply_to => ...,...}) line 6 in context child_terminated
2019-07-31 19:29:54.441 [error] <0.1090.0>@Elixir.Events:handle_in:6 gen_server 'Elixir.Events' terminated with reason: no function clause matching 'Elixir.Events':handle_in(#{'__struct__' => 'Elixir.Requests.RequestAThing',context => #{},correlation_id => <<>>,reply_to => ...,...}) line 6
2019-07-31 19:29:54.447 [error] <0.1090.0>@Elixir.Events:handle_in:6 CRASH REPORT Process 'Elixir.Events' with 0 neighbours crashed with reason: no function clause matching 'Elixir.Events':handle_in(#{'__struct__' => 'Elixir.Requests.RequestAThing',context => #{},correlation_id => <<>>,reply_to => ...,...}) line 6
2019-07-31 19:29:54.447 [error] <0.1088.0>@Elixir.Events:handle_in:6 Supervisor 'Elixir.RailwayIpc.Consumer.Supervisor' had child 'Elixir.Events' started with 'Elixir.Events':start_link([]) at <0.1090.0> exit with reason no function clause matching 'Elixir.Events':handle_in(#{'__struct__' => 'Elixir.Requests.RequestAThing',context => #{},correlation_id => <<>>,reply_to => ...,...}) line 6 in context child_terminated
2019-07-31 19:31:11.204 [error] <0.297.0>@Elixir.Events:handle_in:6 gen_server 'Elixir.Events' terminated with reason: no function clause matching 'Elixir.Events':handle_in(#{'__struct__' => 'Elixir.Requests.RequestAThing',context => #{},correlation_id => <<>>,reply_to => ...,...}) line 6
2019-07-31 19:31:11.216 [error] <0.297.0>@Elixir.Events:handle_in:6 CRASH REPORT Process 'Elixir.Events' with 0 neighbours crashed with reason: no function clause matching 'Elixir.Events':handle_in(#{'__struct__' => 'Elixir.Requests.RequestAThing',context => #{},correlation_id => <<>>,reply_to => ...,...}) line 6
2019-07-31 19:31:11.216 [error] <0.295.0>@Elixir.Events:handle_in:6 Supervisor 'Elixir.RailwayIpc.Consumer.Supervisor' had child 'Elixir.Events' started with 'Elixir.Events':start_link([]) at <0.297.0> exit with reason no function clause matching 'Elixir.Events':handle_in(#{'__struct__' => 'Elixir.Requests.RequestAThing',context => #{},correlation_id => <<>>,reply_to => ...,...}) line 6 in context child_terminated
2019-07-31 19:35:15.622 [error] <0.298.0>@Elixir.RailwayIpc.Core.RequestsConsumer:post_processing:18 gen_server 'Elixir.Requests' terminated with reason: no function clause matching 'Elixir.RailwayIpc.Core.RequestsConsumer':post_processing(ok, #{'__struct__' => 'Elixir.Events.AThingWasDone',context => #{},correlation_id => <<>>,user_uuid => <<>>,...}, #Fun<Elixir.Requests.0.79135101>, #Fun<Elixir.Requests.1.79135101>) line 18
2019-07-31 19:35:15.630 [error] <0.298.0>@Elixir.RailwayIpc.Core.RequestsConsumer:post_processing:18 CRASH REPORT Process 'Elixir.Requests' with 0 neighbours crashed with reason: no function clause matching 'Elixir.RailwayIpc.Core.RequestsConsumer':post_processing(ok, #{'__struct__' => 'Elixir.Events.AThingWasDone',context => #{},correlation_id => <<>>,user_uuid => <<>>,...}, #Fun<Elixir.Requests.0.79135101>, #Fun<Elixir.Requests.1.79135101>) line 18
2019-07-31 19:35:15.630 [error] <0.295.0>@Elixir.RailwayIpc.Core.RequestsConsumer:post_processing:18 Supervisor 'Elixir.RailwayIpc.Consumer.Supervisor' had child 'Elixir.Requests' started with 'Elixir.Requests':start_link([]) at <0.298.0> exit with reason no function clause matching 'Elixir.RailwayIpc.Core.RequestsConsumer':post_processing(ok, #{'__struct__' => 'Elixir.Events.AThingWasDone',context => #{},correlation_id => <<>>,user_uuid => <<>>,...}, #Fun<Elixir.Requests.0.79135101>, #Fun<Elixir.Requests.1.79135101>) line 18 in context child_terminated
2019-07-31 19:36:37.382 [error] <0.297.0>@Elixir.RailwayIpc.Core.RequestsConsumer:post_processing:18 gen_server 'Elixir.Events' terminated with reason: no function clause matching 'Elixir.RailwayIpc.Core.RequestsConsumer':post_processing(ok, #{'__struct__' => 'Elixir.Events.AThingWasDone',context => #{},correlation_id => <<>>,user_uuid => <<>>,...}, #Fun<Elixir.Events.0.91040133>, #Fun<Elixir.Events.1.91040133>) line 18
2019-07-31 19:36:37.383 [error] <0.297.0>@Elixir.RailwayIpc.Core.RequestsConsumer:post_processing:18 CRASH REPORT Process 'Elixir.Events' with 0 neighbours crashed with reason: no function clause matching 'Elixir.RailwayIpc.Core.RequestsConsumer':post_processing(ok, #{'__struct__' => 'Elixir.Events.AThingWasDone',context => #{},correlation_id => <<>>,user_uuid => <<>>,...}, #Fun<Elixir.Events.0.91040133>, #Fun<Elixir.Events.1.91040133>) line 18
2019-07-31 19:36:37.383 [error] <0.295.0>@Elixir.RailwayIpc.Core.RequestsConsumer:post_processing:18 Supervisor 'Elixir.RailwayIpc.Consumer.Supervisor' had child 'Elixir.Events' started with 'Elixir.Events':start_link([]) at <0.297.0> exit with reason no function clause matching 'Elixir.RailwayIpc.Core.RequestsConsumer':post_processing(ok, #{'__struct__' => 'Elixir.Events.AThingWasDone',context => #{},correlation_id => <<>>,user_uuid => <<>>,...}, #Fun<Elixir.Events.0.91040133>, #Fun<Elixir.Events.1.91040133>) line 18 in context child_terminated
2019-07-31 19:37:47.781 [error] <0.278.0>@Elixir.RailwayIpc.Core.RequestsConsumer:post_processing:18 gen_server 'Elixir.Events' terminated with reason: no function clause matching 'Elixir.RailwayIpc.Core.RequestsConsumer':post_processing(ok, #{'__struct__' => 'Elixir.Events.AThingWasDone',context => #{},correlation_id => <<>>,user_uuid => <<>>,...}, #Fun<Elixir.Events.0.91040133>, #Fun<Elixir.Events.1.91040133>) line 18
2019-07-31 19:37:47.786 [error] <0.278.0>@Elixir.RailwayIpc.Core.RequestsConsumer:post_processing:18 CRASH REPORT Process 'Elixir.Events' with 0 neighbours crashed with reason: no function clause matching 'Elixir.RailwayIpc.Core.RequestsConsumer':post_processing(ok, #{'__struct__' => 'Elixir.Events.AThingWasDone',context => #{},correlation_id => <<>>,user_uuid => <<>>,...}, #Fun<Elixir.Events.0.91040133>, #Fun<Elixir.Events.1.91040133>) line 18
2019-07-31 19:37:47.786 [error] <0.276.0>@Elixir.RailwayIpc.Core.RequestsConsumer:post_processing:18 Supervisor 'Elixir.RailwayIpc.Consumer.Supervisor' had child 'Elixir.Events' started with 'Elixir.Events':start_link([]) at <0.278.0> exit with reason no function clause matching 'Elixir.RailwayIpc.Core.RequestsConsumer':post_processing(ok, #{'__struct__' => 'Elixir.Events.AThingWasDone',context => #{},correlation_id => <<>>,user_uuid => <<>>,...}, #Fun<Elixir.Events.0.91040133>, #Fun<Elixir.Events.1.91040133>) line 18 in context child_terminated
